"""FastAPI server for the AthleteCare RAG Service."""

from __future__ import annotations

import logging

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from app.config import CHROMA_DIR, MODEL_PATH
from app.rag_engine import generate_insight

logger = logging.getLogger(__name__)

app = FastAPI(
    title="AthleteCare RAG Service",
    description=(
        "Local Retrieval-Augmented Generation service for sports medicine "
        "clinical insights. Searches club medical protocols and past injury "
        "cases using hybrid search (ChromaDB + BM25)."
    ),
    version="1.0.0",
)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------
class QueryRequest(BaseModel):
    description: str = Field(
        ...,
        min_length=10,
        description="Injury report or clinical query text",
        examples=[
            "Player reports sharp pain in the posterior calf during sprinting, "
            "unable to continue training."
        ],
    )


class QueryResponse(BaseModel):
    similar_listings: list[str]
    insight: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.get("/health")
def health():
    """Readiness check – reports vector store and model availability."""
    return {
        "status": "ok",
        "chroma_db_exists": CHROMA_DIR.exists(),
        "model_exists": MODEL_PATH.exists(),
    }


@app.post("/query", response_model=QueryResponse)
def query(body: QueryRequest) -> QueryResponse:
    """
    Accept an injury description, retrieve similar cases/protocols,
    and return a clinical insight generated by the local LLM.
    """
    description = body.description.strip()
    if not description:
        raise HTTPException(status_code=422, detail="Description must not be empty.")

    if not CHROMA_DIR.exists():
        raise HTTPException(
            status_code=503,
            detail=(
                "Vector store not found. Run 'python -m app.ingest' first to "
                "populate ChromaDB."
            ),
        )

    try:
        result = generate_insight(description)
        return QueryResponse(**result)
    except FileNotFoundError as exc:
        logger.error("Model file missing: %s", exc)
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except Exception as exc:
        logger.exception("Unexpected error during query processing")
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate insight: {exc}",
        ) from exc
